/*
Copyright (c) 2013, Washington University in St.Louis.
All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.17 at 06:25:05 AM BST 
//


package gme.cacore_cacore._3_2.edu_northwestern_radiology;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gme.cacore_cacore._3_2.edu_northwestern_radiology package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ImageAnnotation_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIM", "ImageAnnotation");
    private final static QName _AnnotationOfAnnotation_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIM", "AnnotationOfAnnotation");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gme.cacore_cacore._3_2.edu_northwestern_radiology
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link TextAnnotation }
     * 
     */
    public TextAnnotation createTextAnnotation() {
        return new TextAnnotation();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.AnnotationRole }
     * 
     */
    public gme.cacore_cacore._3_2.edu_northwestern_radiology.AnnotationRole createAnnotationRole() {
        return new gme.cacore_cacore._3_2.edu_northwestern_radiology.AnnotationRole();
    }

    /**
     * Create an instance of {@link Circle }
     * 
     */
    public Circle createCircle() {
        return new Circle();
    }

    /**
     * Create an instance of {@link Calculation.ReferencedCalculationCollection }
     * 
     */
    public Calculation.ReferencedCalculationCollection createCalculationReferencedCalculationCollection() {
        return new Calculation.ReferencedCalculationCollection();
    }

    /**
     * Create an instance of {@link WebImageReference }
     * 
     */
    public WebImageReference createWebImageReference() {
        return new WebImageReference();
    }

    /**
     * Create an instance of {@link ImageAnnotation.Patient }
     * 
     */
    public ImageAnnotation.Patient createImageAnnotationPatient() {
        return new ImageAnnotation.Patient();
    }

    /**
     * Create an instance of {@link Calculation.CalculationResultCollection }
     * 
     */
    public Calculation.CalculationResultCollection createCalculationCalculationResultCollection() {
        return new Calculation.CalculationResultCollection();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.Segmentation.ImagingObservation }
     * 
     */
    public gme.cacore_cacore._3_2.edu_northwestern_radiology.Segmentation.ImagingObservation createSegmentationImagingObservation() {
        return new gme.cacore_cacore._3_2.edu_northwestern_radiology.Segmentation.ImagingObservation();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.MultiPoint }
     * 
     */
    public gme.cacore_cacore._3_2.edu_northwestern_radiology.MultiPoint createMultiPoint() {
        return new gme.cacore_cacore._3_2.edu_northwestern_radiology.MultiPoint();
    }

    /**
     * Create an instance of {@link AnnotationOfAnnotation }
     * 
     */
    public AnnotationOfAnnotation createAnnotationOfAnnotation() {
        return new AnnotationOfAnnotation();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.Series.ImageCollection }
     * 
     */
    public gme.cacore_cacore._3_2.edu_northwestern_radiology.Series.ImageCollection createSeriesImageCollection() {
        return new gme.cacore_cacore._3_2.edu_northwestern_radiology.Series.ImageCollection();
    }

    /**
     * Create an instance of {@link ThreeDimensionSpatialCoordinate }
     * 
     */
    public ThreeDimensionSpatialCoordinate createThreeDimensionSpatialCoordinate() {
        return new ThreeDimensionSpatialCoordinate();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link ImageAnnotation.InferenceCollection }
     * 
     */
    public ImageAnnotation.InferenceCollection createImageAnnotationInferenceCollection() {
        return new ImageAnnotation.InferenceCollection();
    }

    /**
     * Create an instance of {@link AnatomicEntity }
     * 
     */
    public AnatomicEntity createAnatomicEntity() {
        return new AnatomicEntity();
    }

    /**
     * Create an instance of {@link ReferencedCalculation }
     * 
     */
    public ReferencedCalculation createReferencedCalculation() {
        return new ReferencedCalculation();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.ImagingObservation.Segmentation }
     * 
     */
    public gme.cacore_cacore._3_2.edu_northwestern_radiology.ImagingObservation.Segmentation createImagingObservationSegmentation() {
        return new gme.cacore_cacore._3_2.edu_northwestern_radiology.ImagingObservation.Segmentation();
    }

    /**
     * Create an instance of {@link ReferencedAnnotation.AnnotationRole }
     * 
     */
    public ReferencedAnnotation.AnnotationRole createReferencedAnnotationAnnotationRole() {
        return new ReferencedAnnotation.AnnotationRole();
    }

    /**
     * Create an instance of {@link Calculation }
     * 
     */
    public Calculation createCalculation() {
        return new Calculation();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.Annotation.User }
     * 
     */
    public gme.cacore_cacore._3_2.edu_northwestern_radiology.Annotation.User createAnnotationUser() {
        return new gme.cacore_cacore._3_2.edu_northwestern_radiology.Annotation.User();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.Annotation.AnatomicEntityCollection }
     * 
     */
    public gme.cacore_cacore._3_2.edu_northwestern_radiology.Annotation.AnatomicEntityCollection createAnnotationAnatomicEntityCollection() {
        return new gme.cacore_cacore._3_2.edu_northwestern_radiology.Annotation.AnatomicEntityCollection();
    }

    /**
     * Create an instance of {@link Point }
     * 
     */
    public Point createPoint() {
        return new Point();
    }

    /**
     * Create an instance of {@link AnnotationOfAnnotation.ReferencedAnnotationCollection }
     * 
     */
    public AnnotationOfAnnotation.ReferencedAnnotationCollection createAnnotationOfAnnotationReferencedAnnotationCollection() {
        return new AnnotationOfAnnotation.ReferencedAnnotationCollection();
    }

    /**
     * Create an instance of {@link ImageAnnotation.TextAnnotationCollection }
     * 
     */
    public ImageAnnotation.TextAnnotationCollection createImageAnnotationTextAnnotationCollection() {
        return new ImageAnnotation.TextAnnotationCollection();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.User }
     * 
     */
    public gme.cacore_cacore._3_2.edu_northwestern_radiology.User createUser() {
        return new gme.cacore_cacore._3_2.edu_northwestern_radiology.User();
    }

    /**
     * Create an instance of {@link Ellipse }
     * 
     */
    public Ellipse createEllipse() {
        return new Ellipse();
    }

    /**
     * Create an instance of {@link CalculationResult }
     * 
     */
    public CalculationResult createCalculationResult() {
        return new CalculationResult();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.Rating }
     * 
     */
    public gme.cacore_cacore._3_2.edu_northwestern_radiology.Rating createRating() {
        return new gme.cacore_cacore._3_2.edu_northwestern_radiology.Rating();
    }

    /**
     * Create an instance of {@link CalculationResult.DimensionCollection }
     * 
     */
    public CalculationResult.DimensionCollection createCalculationResultDimensionCollection() {
        return new CalculationResult.DimensionCollection();
    }

    /**
     * Create an instance of {@link Coordinate }
     * 
     */
    public Coordinate createCoordinate() {
        return new Coordinate();
    }

    /**
     * Create an instance of {@link Inference }
     * 
     */
    public Inference createInference() {
        return new Inference();
    }

    /**
     * Create an instance of {@link CalculationResult.DataCollection }
     * 
     */
    public CalculationResult.DataCollection createCalculationResultDataCollection() {
        return new CalculationResult.DataCollection();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.Series }
     * 
     */
    public gme.cacore_cacore._3_2.edu_northwestern_radiology.Series createSeries() {
        return new gme.cacore_cacore._3_2.edu_northwestern_radiology.Series();
    }

    /**
     * Create an instance of {@link ImageAnnotation }
     * 
     */
    public ImageAnnotation createImageAnnotation() {
        return new ImageAnnotation();
    }

    /**
     * Create an instance of {@link Calculation.ReferencedGeometricShapeCollection }
     * 
     */
    public Calculation.ReferencedGeometricShapeCollection createCalculationReferencedGeometricShapeCollection() {
        return new Calculation.ReferencedGeometricShapeCollection();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.GeometricShape.SpatialCoordinateCollection }
     * 
     */
    public gme.cacore_cacore._3_2.edu_northwestern_radiology.GeometricShape.SpatialCoordinateCollection createGeometricShapeSpatialCoordinateCollection() {
        return new gme.cacore_cacore._3_2.edu_northwestern_radiology.GeometricShape.SpatialCoordinateCollection();
    }

    /**
     * Create an instance of {@link Data.CoordinateCollection }
     * 
     */
    public Data.CoordinateCollection createDataCoordinateCollection() {
        return new Data.CoordinateCollection();
    }

    /**
     * Create an instance of {@link AnatomicEntityCharacteristic.Rating }
     * 
     */
    public AnatomicEntityCharacteristic.Rating createAnatomicEntityCharacteristicRating() {
        return new AnatomicEntityCharacteristic.Rating();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.ImagingObservation.ImagingObservationCharacteristicCollection }
     * 
     */
    public gme.cacore_cacore._3_2.edu_northwestern_radiology.ImagingObservation.ImagingObservationCharacteristicCollection createImagingObservationImagingObservationCharacteristicCollection() {
        return new gme.cacore_cacore._3_2.edu_northwestern_radiology.ImagingObservation.ImagingObservationCharacteristicCollection();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.Study.Series }
     * 
     */
    public gme.cacore_cacore._3_2.edu_northwestern_radiology.Study.Series createStudySeries() {
        return new gme.cacore_cacore._3_2.edu_northwestern_radiology.Study.Series();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.ImagingObservation }
     * 
     */
    public gme.cacore_cacore._3_2.edu_northwestern_radiology.ImagingObservation createImagingObservation() {
        return new gme.cacore_cacore._3_2.edu_northwestern_radiology.ImagingObservation();
    }

    /**
     * Create an instance of {@link TwoDimensionSpatialCoordinate }
     * 
     */
    public TwoDimensionSpatialCoordinate createTwoDimensionSpatialCoordinate() {
        return new TwoDimensionSpatialCoordinate();
    }

    /**
     * Create an instance of {@link ImagingObservationCharacteristic }
     * 
     */
    public ImagingObservationCharacteristic createImagingObservationCharacteristic() {
        return new ImagingObservationCharacteristic();
    }

    /**
     * Create an instance of {@link Polyline }
     * 
     */
    public Polyline createPolyline() {
        return new Polyline();
    }

    /**
     * Create an instance of {@link ImageAnnotation.GeometricShapeCollection }
     * 
     */
    public ImageAnnotation.GeometricShapeCollection createImageAnnotationGeometricShapeCollection() {
        return new ImageAnnotation.GeometricShapeCollection();
    }

    /**
     * Create an instance of {@link ReferencedAnnotation }
     * 
     */
    public ReferencedAnnotation createReferencedAnnotation() {
        return new ReferencedAnnotation();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.Annotation.CalculationCollection }
     * 
     */
    public gme.cacore_cacore._3_2.edu_northwestern_radiology.Annotation.CalculationCollection createAnnotationCalculationCollection() {
        return new gme.cacore_cacore._3_2.edu_northwestern_radiology.Annotation.CalculationCollection();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.Segmentation }
     * 
     */
    public gme.cacore_cacore._3_2.edu_northwestern_radiology.Segmentation createSegmentation() {
        return new gme.cacore_cacore._3_2.edu_northwestern_radiology.Segmentation();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.Annotation.Equipment }
     * 
     */
    public gme.cacore_cacore._3_2.edu_northwestern_radiology.Annotation.Equipment createAnnotationEquipment() {
        return new gme.cacore_cacore._3_2.edu_northwestern_radiology.Annotation.Equipment();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.Annotation.ImagingObservationCollection }
     * 
     */
    public gme.cacore_cacore._3_2.edu_northwestern_radiology.Annotation.ImagingObservationCollection createAnnotationImagingObservationCollection() {
        return new gme.cacore_cacore._3_2.edu_northwestern_radiology.Annotation.ImagingObservationCollection();
    }

    /**
     * Create an instance of {@link Dimension }
     * 
     */
    public Dimension createDimension() {
        return new Dimension();
    }

    /**
     * Create an instance of {@link ImagingObservationCharacteristic.Rating }
     * 
     */
    public ImagingObservationCharacteristic.Rating createImagingObservationCharacteristicRating() {
        return new ImagingObservationCharacteristic.Rating();
    }

    /**
     * Create an instance of {@link DICOMImageReference }
     * 
     */
    public DICOMImageReference createDICOMImageReference() {
        return new DICOMImageReference();
    }

    /**
     * Create an instance of {@link ImageAnnotation.ImageReferenceCollection }
     * 
     */
    public ImageAnnotation.ImageReferenceCollection createImageAnnotationImageReferenceCollection() {
        return new ImageAnnotation.ImageReferenceCollection();
    }

    /**
     * Create an instance of {@link AnatomicEntityCharacteristic }
     * 
     */
    public AnatomicEntityCharacteristic createAnatomicEntityCharacteristic() {
        return new AnatomicEntityCharacteristic();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.Study }
     * 
     */
    public gme.cacore_cacore._3_2.edu_northwestern_radiology.Study createStudy() {
        return new gme.cacore_cacore._3_2.edu_northwestern_radiology.Study();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.Patient }
     * 
     */
    public gme.cacore_cacore._3_2.edu_northwestern_radiology.Patient createPatient() {
        return new gme.cacore_cacore._3_2.edu_northwestern_radiology.Patient();
    }

    /**
     * Create an instance of {@link ReferencedGeometricShape }
     * 
     */
    public ReferencedGeometricShape createReferencedGeometricShape() {
        return new ReferencedGeometricShape();
    }

    /**
     * Create an instance of {@link DICOMImageReference.Study }
     * 
     */
    public DICOMImageReference.Study createDICOMImageReferenceStudy() {
        return new DICOMImageReference.Study();
    }

    /**
     * Create an instance of {@link TextAnnotation.MultiPoint }
     * 
     */
    public TextAnnotation.MultiPoint createTextAnnotationMultiPoint() {
        return new TextAnnotation.MultiPoint();
    }

    /**
     * Create an instance of {@link ImageAnnotation.SegmentationCollection }
     * 
     */
    public ImageAnnotation.SegmentationCollection createImageAnnotationSegmentationCollection() {
        return new ImageAnnotation.SegmentationCollection();
    }

    /**
     * Create an instance of {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.Equipment }
     * 
     */
    public gme.cacore_cacore._3_2.edu_northwestern_radiology.Equipment createEquipment() {
        return new gme.cacore_cacore._3_2.edu_northwestern_radiology.Equipment();
    }

    /**
     * Create an instance of {@link AnatomicEntity.AnatomicEntityCharacteristicCollection }
     * 
     */
    public AnatomicEntity.AnatomicEntityCharacteristicCollection createAnatomicEntityAnatomicEntityCharacteristicCollection() {
        return new AnatomicEntity.AnatomicEntityCharacteristicCollection();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImageAnnotation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIM", name = "ImageAnnotation")
    public JAXBElement<ImageAnnotation> createImageAnnotation(ImageAnnotation value) {
        return new JAXBElement<ImageAnnotation>(_ImageAnnotation_QNAME, ImageAnnotation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnotationOfAnnotation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIM", name = "AnnotationOfAnnotation")
    public JAXBElement<AnnotationOfAnnotation> createAnnotationOfAnnotation(AnnotationOfAnnotation value) {
        return new JAXBElement<AnnotationOfAnnotation>(_AnnotationOfAnnotation_QNAME, AnnotationOfAnnotation.class, null, value);
    }

}
