//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.17 at 06:25:05 AM BST 
//


package gme.cacore_cacore._3_2.edu_northwestern_radiology;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReferencedAnnotation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReferencedAnnotation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="annotationRole" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AnnotationRole" type="{gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIM}AnnotationRole" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="referencedAnnotationUID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReferencedAnnotation", propOrder = {
    "annotationRole"
})
public class ReferencedAnnotation {

    protected ReferencedAnnotation.AnnotationRole annotationRole;
    @XmlAttribute(required = true)
    protected BigInteger id;
    @XmlAttribute(required = true)
    protected String referencedAnnotationUID;

    /**
     * Gets the value of the annotationRole property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencedAnnotation.AnnotationRole }
     *     
     */
    public ReferencedAnnotation.AnnotationRole getAnnotationRole() {
        return annotationRole;
    }

    /**
     * Sets the value of the annotationRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencedAnnotation.AnnotationRole }
     *     
     */
    public void setAnnotationRole(ReferencedAnnotation.AnnotationRole value) {
        this.annotationRole = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the referencedAnnotationUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferencedAnnotationUID() {
        return referencedAnnotationUID;
    }

    /**
     * Sets the value of the referencedAnnotationUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferencedAnnotationUID(String value) {
        this.referencedAnnotationUID = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AnnotationRole" type="{gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIM}AnnotationRole" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "annotationRole"
    })
    public static class AnnotationRole {

        @XmlElement(name = "AnnotationRole")
        protected gme.cacore_cacore._3_2.edu_northwestern_radiology.AnnotationRole annotationRole;

        /**
         * Gets the value of the annotationRole property.
         * 
         * @return
         *     possible object is
         *     {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.AnnotationRole }
         *     
         */
        public gme.cacore_cacore._3_2.edu_northwestern_radiology.AnnotationRole getAnnotationRole() {
            return annotationRole;
        }

        /**
         * Sets the value of the annotationRole property.
         * 
         * @param value
         *     allowed object is
         *     {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.AnnotationRole }
         *     
         */
        public void setAnnotationRole(gme.cacore_cacore._3_2.edu_northwestern_radiology.AnnotationRole value) {
            this.annotationRole = value;
        }

    }

}
