/*
Copyright (c) 2013, Washington University in St.Louis.
All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.17 at 06:25:05 AM BST 
//


package gme.cacore_cacore._3_2.edu_northwestern_radiology;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Segmentation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Segmentation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="imagingObservation" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ImagingObservation" type="{gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIM}ImagingObservation" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="type" use="required" type="{gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIM}SegmentationIdentifier" />
 *       &lt;attribute name="sopInstanceUID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sopClassUID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="referencedSopInstanceUID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="segmentNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Segmentation", propOrder = {
    "imagingObservation"
})
public class Segmentation {

    protected Segmentation.ImagingObservation imagingObservation;
    @XmlAttribute(required = true)
    protected BigInteger id;
    @XmlAttribute(required = true)
    protected SegmentationIdentifier type;
    @XmlAttribute(required = true)
    protected String sopInstanceUID;
    @XmlAttribute(required = true)
    protected String sopClassUID;
    @XmlAttribute(required = true)
    protected String referencedSopInstanceUID;
    @XmlAttribute(required = true)
    protected BigInteger segmentNumber;

    /**
     * Gets the value of the imagingObservation property.
     * 
     * @return
     *     possible object is
     *     {@link Segmentation.ImagingObservation }
     *     
     */
    public Segmentation.ImagingObservation getImagingObservation() {
        return imagingObservation;
    }

    /**
     * Sets the value of the imagingObservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Segmentation.ImagingObservation }
     *     
     */
    public void setImagingObservation(Segmentation.ImagingObservation value) {
        this.imagingObservation = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link SegmentationIdentifier }
     *     
     */
    public SegmentationIdentifier getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link SegmentationIdentifier }
     *     
     */
    public void setType(SegmentationIdentifier value) {
        this.type = value;
    }

    /**
     * Gets the value of the sopInstanceUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSopInstanceUID() {
        return sopInstanceUID;
    }

    /**
     * Sets the value of the sopInstanceUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSopInstanceUID(String value) {
        this.sopInstanceUID = value;
    }

    /**
     * Gets the value of the sopClassUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSopClassUID() {
        return sopClassUID;
    }

    /**
     * Sets the value of the sopClassUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSopClassUID(String value) {
        this.sopClassUID = value;
    }

    /**
     * Gets the value of the referencedSopInstanceUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferencedSopInstanceUID() {
        return referencedSopInstanceUID;
    }

    /**
     * Sets the value of the referencedSopInstanceUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferencedSopInstanceUID(String value) {
        this.referencedSopInstanceUID = value;
    }

    /**
     * Gets the value of the segmentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSegmentNumber() {
        return segmentNumber;
    }

    /**
     * Sets the value of the segmentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSegmentNumber(BigInteger value) {
        this.segmentNumber = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ImagingObservation" type="{gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIM}ImagingObservation" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "imagingObservation"
    })
    public static class ImagingObservation {

        @XmlElement(name = "ImagingObservation")
        protected gme.cacore_cacore._3_2.edu_northwestern_radiology.ImagingObservation imagingObservation;

        /**
         * Gets the value of the imagingObservation property.
         * 
         * @return
         *     possible object is
         *     {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.ImagingObservation }
         *     
         */
        public gme.cacore_cacore._3_2.edu_northwestern_radiology.ImagingObservation getImagingObservation() {
            return imagingObservation;
        }

        /**
         * Sets the value of the imagingObservation property.
         * 
         * @param value
         *     allowed object is
         *     {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.ImagingObservation }
         *     
         */
        public void setImagingObservation(gme.cacore_cacore._3_2.edu_northwestern_radiology.ImagingObservation value) {
            this.imagingObservation = value;
        }

    }

}
